#!/bin/bash

if [ -z "$1" ]
then
	pattern=".*err"
else
	pattern=$1
fi      

echo "pattern is:"
echo $pattern
for f in $(find ./* -maxdepth 1 -mindepth 1 | grep "${pattern}$"); do
  printf "$f\t$(cat $f | grep "Exit status")\n"
done
