#!/bin/bash

pattern=$1 # example pattern: .*abyss.*err or .*err
echo "pattern is:"
echo $pattern
for f in $(find ./* -maxdepth 1 -mindepth 1 | grep "${pattern}$"); do
  printf "$f\t$(cat $f | grep "Exit status")\n"
done
